carrent/carrent/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('carrent/', include('carrentapp.urls')),
    path('account/', include('accounts.urls')),
    path('employee/', include('employee.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carrent/carrentapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.generic import ListView, DetailView, TemplateView


from carrentapp.views import base_test_view, CreateOrderView, FutureOrderView,\
                                HistoryOrderView, ActualOrderView, PickOrderDate,\
                                OrderUpdateView, OrderDeleteView, OrderDetailView, CarListView
from carrentapp.models import Car

urlpatterns = [
    path('base-test/', base_test_view, name='zalogowany'),
    path('carlist/', CarListView.as_view(), name='car_list'),
    path('cardetail/<int:pk>/', DetailView.as_view(model=Car), name="car_detail"),
    path('', TemplateView.as_view(template_name='carrentapp/home_page.html'), name='main'),
    path('contact', TemplateView.as_view(template_name='carrentapp/contact.html'), name='contact'),
    path('aboutus', TemplateView.as_view(template_name='carrentapp/about.html'), name='about'),
    path('order/<int:pk>/', PickOrderDate.as_view(), name='order'),
    path('order/<int:pk>/<str:msg>/', PickOrderDate.as_view(), name='order_msg'),
    path('order-confirm/', CreateOrderView.as_view(), name='order_confirm'),
    path('order-detail/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('order-delete/<int:pk>/', OrderDeleteView.as_view(), name='order_delete'),
    path('order-actual/', ActualOrderView.as_view(), name='actual_order'),
    path('order-history/', HistoryOrderView.as_view(), name='history_order'),
    path('order-future/', FutureOrderView.as_view(), name='future_order'),
    path('order-update/<int:pk>', OrderUpdateView.as_view(), name='order_update'),
    path('order-update/<int:pk>/<str:msg>/', OrderUpdateView.as_view(), name='order_update_msg'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carrent/carrentapp/models.py
from datetime import date

from django.db import models

from accounts.models import UserCustom
from carrentapp.enums import CarEngineType, CarGearboxType, OrderStatus
from carrentapp.utilities import calculate_cost


class CarBrand(models.Model):
    brand_name = models.CharField(max_length=50, verbose_name="Marka", unique=True)

    class Meta:
        verbose_name = "Marka"
        verbose_name_plural = "Marki"

    def __str__(self):
        return f'{self.brand_name}'


class CarModel(models.Model):
    model_name = models.CharField(max_length=50, verbose_name="Model")
    brand = models.ForeignKey(CarBrand, verbose_name="Marka", on_delete=models.PROTECT)

    class Meta:
        verbose_name = "Model"
        verbose_name_plural = "Modele"

    def __str__(self):
        return f'{self.model_name}'


class Car(models.Model):
    plate_number = models.CharField(max_length=20, verbose_name="Numer rejestracyjny", unique=True)
    brand = models.ForeignKey(CarBrand, verbose_name="Marka", on_delete=models.PROTECT)
    car_model = models.ForeignKey(CarModel, verbose_name="Model", on_delete=models.PROTECT)

    year_of_production = models.IntegerField(verbose_name="Rok produkcji")
    rating = models.FloatField(verbose_name="Ocena")
    number_of_seats = models.IntegerField(verbose_name="Ilość miejsc")
    engine_type = models.CharField(max_length=2, verbose_name="Rodzaj silnika",
                                   choices=CarEngineType.choices)
    engine_power = models.IntegerField(verbose_name="Moc")
    color = models.CharField(max_length=20, verbose_name="Kolor")
    car_mileage = models.IntegerField(verbose_name="Przebieg")
    car_image = models.ImageField(upload_to='images/cars', verbose_name="Zdjęcie")
    gearbox_type = models.CharField(max_length=1, verbose_name="Skrzynia biegów", choices=CarGearboxType.choices)

    class Meta:
        verbose_name = "Samochód"
        verbose_name_plural = "Samochody"

    def __str__(self):
        return f'{self.plate_number} - {self.brand} {self.car_model}'


class BasePrice(models.Model):
    base_price = models.IntegerField(verbose_name="Cena Bazowa")

    class Meta:
        verbose_name = "Cena Bazowa"
        verbose_name_plural = "Cena Bazowa"

    def __str__(self):
        return f'Cena Bazowa: {self.base_price}'


class Order(models.Model):
    client = models.ForeignKey(UserCustom, verbose_name="Klient", on_delete=models.PROTECT)
    car = models.ForeignKey(Car, verbose_name="Samochód", on_delete=models.PROTECT)
    base_price = models.ForeignKey(BasePrice, verbose_name="Cena bazowa", on_delete=models.PROTECT)

    rent_cost = models.IntegerField(verbose_name="Koszt wynajmu", blank=True, null=True)
    start_date = models.DateField(verbose_name="Start")
    return_date = models.DateField(verbose_name="Zwrot")
    order_length = models.IntegerField(verbose_name="Długość wypożyczenia", default=0)
    kilometers_traveled = models.IntegerField(verbose_name="Przejechane kilometry", default=0)
    order_datetime = models.DateTimeField(verbose_name="Powstanie zamówienia", auto_now_add=True)
    last_modified = models.DateTimeField(verbose_name="Edytowane", auto_now=True)

    status = models.CharField(max_length=1,
                              verbose_name="Status",
                              choices=OrderStatus.choices,
                              default=OrderStatus.AKTYWNY)
    issue_resolved = models.BooleanField(verbose_name="Problem rozwiązany", null=True)

    class Meta:
        verbose_name = "Log Wypozyczenia"
        verbose_name_plural = "Logi Wypozyczen"

    def __str__(self):
        return f'{self.client.email} {self.car.plate_number} =>ID {self.id}'

    @property
    def cost_calculator(self):
        base_price = self.base_price.base_price
        car_rating = self.car.rating
        time_discount = TimeDiscount.objects.last()
        car_discount_obj = BrandDiscount.objects.last()
        if car_discount_obj.car_brand == self.car.brand:
            car_discount = car_discount_obj.brand_discount
        else:
            car_discount = 0
        user_discount = self.client.get_user_discount
        cost = calculate_cost(self.start_date,
                              self.return_date,
                              base_price,
                              car_rating, user_discount, time_discount, car_discount)
        return cost

    @property
    def is_future(self):
        if self.start_date > date.today():
            return True
        else:
            return False

    @property
    def is_past(self):
        if self.return_date < date.today():
            return True
        else:
            return False

    def save(self, *args, **kwarg):
        self.rent_cost = self.cost_calculator
        self.order_length = (self.return_date - self.start_date).days
        super(Order, self).save(*args, **kwarg)


class TimeDiscount(models.Model):
    month_discount = models.IntegerField(verbose_name="Zniżka miesięczna")
    two_weeks_discount = models.IntegerField(verbose_name="Zniżka dwutygodniowa")

    class Meta:
        verbose_name = "Zniżka czasowa"
        verbose_name_plural = "Zniżka czasowa"

    def __str__(self):
        return 'Zniżka czasowa'


class BrandDiscount(models.Model):
    car_brand = models.ForeignKey(CarBrand, on_delete=models.PROTECT, null=True)
    brand_discount = models.IntegerField(verbose_name="Zniżka na marke")

    class Meta:
        verbose_name = "Zniżka marki"
        verbose_name_plural = "Zniżka marki"

    def __str__(self):
        return f'Zniżka czasowa {self.car_brand}'


class BaseUserDiscount(models.Model):
    max_discount = models.IntegerField(verbose_name="Maksymalna zniżka")
    increment_per_tick = models.IntegerField(verbose_name="Skok zniżki")
    orders_per_tick = models.IntegerField(verbose_name="Co ile zamówień skok")
    min_order_length = models.IntegerField(verbose_name="Minimalna długość zamówienia")

    class Meta:
        verbose_name = "Zniżka klienta"
        verbose_name_plural = "Zniżka klienta"

    def __str__(self):
        return 'Zniżka klienta'

carrent/carrentapp/forms.py
from django import forms

from carrentapp.models import Order


class OrderDateForm(forms.Form):
    start_date = forms.DateField(required=True,
                                 widget=forms.DateInput(attrs={'class': 'form-control',
                                                               'type': 'date',
                                                               'style': 'font-size: large'}))
    return_date = forms.DateField(required=True,
                                  widget=forms.DateInput(attrs={'class': 'form-control',
                                                                'type': 'date',
                                                                'style': 'font-size: large'}))


class OrderCreationForm(forms.ModelForm):
    start_date = forms.DateField(required=True,
                                 disabled=True,
                                 widget=forms.DateInput(attrs={'class': 'form-control',
                                                               'type': 'date'}))
    return_date = forms.DateField(required=True,
                                  disabled=True,
                                  widget=forms.DateInput(attrs={'class': 'form-control',
                                                                'type': 'date'}))

    class Meta:
        model = Order
        fields = ['start_date', 'return_date']


class OrderUpdateForm(forms.ModelForm):
    start_date = forms.DateField(required=True,
                                 widget=forms.DateInput(attrs={'class': 'form-control',
                                                               'type': 'date',
                                                                'style': 'font-size: large'}))
    return_date = forms.DateField(required=True,
                                  widget=forms.DateInput(attrs={'class': 'form-control',
                                                                'type': 'date',
                                                                'style': 'font-size: large'}))

    class Meta:
        model = Order
        fields = ['start_date', 'return_date']


class OrderUpdateFormBlocked(OrderUpdateForm):
    start_date = forms.DateField(required=True,
                                 disabled=True,
                                 widget=forms.DateInput(attrs={'class': 'form-control',
                                                               'type': 'date',
                                                               'style': 'font-size: large'}))

    class Meta:
        model = Order
        fields = ['start_date', 'return_date']

carrent/carrentapp/templates/carrentapp/car_detail.html
{% extends 'carrentapp/base.html' %}

{% block hero_bar %}
    <section class="top-hero projects-hero" xmlns="http://www.w3.org/1999/html">
        <p class="top-hero-text text-light" style="font-size: 8rem; height: 80%">{{ car.brand }} {{ car.car_model }}</p>
        <div class="hero-shadow bg-dark bg-gradient" style="height: 80%"></div>
    </section>
{% endblock %}

{% block section_one %}
    <div class="container border border-dark shadow bg-dark bg-gradient">
        <div class="row justify-content-md-center">
            <div class="col-sm-4 mt-2 mb-2">
                <table class="table table-responsive table-bordered table-hover table-striped table-dark">
                    <tr>
                        <td>Moc KM</td>
                        <td>{{ car.engine_power }}</td>
                    </tr>
                    <tr>
                        <td>Silnik</td>
                        <td>{{ car.get_engine_type_display }}</td>
                    </tr>
                    <tr>
                        <td>Skrzynia biegów</td>
                        <td>{{ car.get_gearbox_type_display }}</td>
                    </tr>
                    <tr>
                        <td>Kolor</td>
                        <td>{{ car.color }}</td>
                    </tr>
                    <tr>
                        <td>Liczba miejsc</td>
                        <td>{{ car.number_of_seats }}</td>
                    </tr>
                    <tr>
                        <td>Rok produkcji</td>
                        <td>{{ car.year_of_production }}</td>
                    </tr>
                </table>
                <a href="{% url 'order' car.id %}" class="btn btn-success btn-lg bg-gradient d-grid gap-2" style="font-size: large">Zarezerwuj ten samochód</a>
            </div>
            <div class="col-sm-8 mb-2 mt-2">
                <img class="img-fluid rounded float-end" src="{{ car.car_image.url }}" alt="{{ car.color }} samochod">
            </div>
        </div>
    </div>
    <div style="height:100vh"></div>
{% endblock %}

carrent/carrentapp/templates/carrentapp/car_list.html
{% extends 'carrentapp/base.html' %}

{% block hero_bar %}
    <section class="top-hero projects-hero" xmlns="http://www.w3.org/1999/html">
        <p class="top-hero-text text-light" style="height: 80%; font-size: xx-large">Nasza flota</p>
        <div class="hero-shadow bg-dark bg-gradient" style="height: 80%"></div>
    </section>
{% endblock %}

{% block section_one %}
    <section class="car_view">
        <section class="car_table">
            <form method="get" class="d-grid gap-2 bg-dark bg-gradient p-2 shadow rounded">
                <table class="table table-responsive table-bordered table-hover table-striped table-dark">
                    <h2 style="color:white; text-align: center">Dostępne Filtry</h2>
                    <tr>
                        <td>Marka</td>
                        <td>{{ filter.form.brand }}</td>
                    </tr>
                    <tr>
                        <td>Model</td>
                        <td>{{ filter.form.car_model }}</td>
                    </tr>
                    <tr>
                        <td>Skrzynia biegów</td>
                        <td>{{ filter.form.gearbox_type }}</td>
                    </tr>
                    <tr>
                        <td>Ilość siedzeń</td>
                        <td>{{ filter.form.number_of_seats }}</td>
                    </tr>
                </table>
                <button name="filtruj" class="btn btn-success btn-lg bg-gradient">Filtruj</button>
            </form>
        </section>
    </section>
    <div style="height:5vh"></div>
    <section class="container">
        <div class="row">
            {% for obj in page_obj %}
                <div class="col-md-6 col-lg-4">
                    <div class="shadow card mb-3 bg-dark bg-gradient">
                        <a href="{% url 'car_detail' obj.id %}"><img class="card-img-top" src="{{ obj.car_image.url }}"></a>
                        <div class="card-body">
                            <div class="d-grid gap-2">
                                <table class="table table-responsive table-bordered table-hover table-striped table-dark">
                                    <tr>
                                        <td>Marka</td>
                                        <td>{{ obj.brand }}</td>
                                    </tr>
                                    <tr>
                                        <td>Model</td>
                                        <td>{{ obj.car_model }}</td>
                                    </tr>
                                    <tr>
                                        <td>Skrzynia biegów</td>
                                        <td>{{ obj.get_gearbox_type_display }}</td>
                                    </tr>
                                    <tr>
                                        <td>Liczba miejsc</td>
                                        <td>{{ obj.number_of_seats }}</td>
                                    </tr>
                                </table>
                                <a href="{% url 'car_detail' obj.id %}" class="shadow btn btn-outline-light px-4" style="font-size: large" role="button">Wypożycz</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% include 'carrentapp/paginator.html' %}
    </section>
    <div style="height:50vh"></div>
{% endblock %}

carrent/carrentapp/templates/carrentapp/contact.html
{% extends 'carrentapp/base.html' %}

{% block section_one %}
    <div class="container border border-dark shadow bg-dark bg-gradient">
        <div class="row justify-content-md-center">
            <div class="col-sm-4 mt-2 mb-2 text-light text-center">
                <h3>Adres:</h3>
                <p class="orange-color">CarRental Wypożyczalnia samochodów</p>
                <p><i class="bi bi-geo-alt"></i> ul. Legnicka 55<br> 53-671 Wrocław</p>
                <p><i class="bi bi-phone"></i>+48 123 456 789</p>
                <p><i class="bi bi-at"></i> CarRental@gmail.com</p>
            </div>
            <div id="map-container-google-1" class="z-depth-1-half map-container col-sm-8 mt-2 mb-2" style="height: 500px">
                <iframe id="gmap_canvas" src="https://maps.google.com/maps?q=Wroc%C5%82aw%20Legnicka%2055&t=&z=13&ie=UTF8&iwloc=&output=embed"
                        style="border:0">
                </iframe>
            </div>
        </div>
    </div>
    <div style="height:100vh"></div>
{% endblock %}

carrent/carrentapp/templates/carrentapp/order_actual.html
{% extends 'carrentapp/base.html' %}

{% block section_one %}
    <div class="container h-100 d-flex flex-column align-items-center text-dark text-center">
        {% if order_list.count < 1 %}
            <div style="height:15vh"></div>
            <h2>Brak wyników do wyświetlenia</h2>
        {% else %}
            <h2>Aktualnie wypożyczone</h2>
            <div style="height:5vh"></div>
            <table class="table table-responsive table-bordered table-hover table-striped table-dark">
                <thead>
                    <tr>
                        <th scope="col">Marka samochodu</th>
                        <th scope="col">Model samochodu</th>
                        <th scope="col">Numer rejestracyjny</th>
                        <th scope="col">Data wypożyczenia</th>
                        <th scope="col">Data zwrotu</th>
                        <th scope="col">Koszt wypożyczenia</th>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <body>
                    {%  for order in order_list  %}
                        <tr class="table-primary">
                            <td> {{ order.car.brand }}</td>
                            <td> {{ order.car.car_model }}  </td>
                            <td> {{ order.car.plate_number }}  </td>
                            <td> {{ order.start_date }}  </td>
                            <td> {{ order.return_date }}  </td>
                            <td> {{ order.rent_cost }}  </td>
                            <td> <a href ="{% url 'order_detail' order.id %}" class="btn btn-info text-nowrap">Szczegóły</a></td>
                            <td> <a href ="{% url 'order_update' order.id %}" class="btn btn-primary text-nowrap">Przedłuż najem</a></td>
                        </tr>
                    {% endfor %}
                </body>

            </table>
        {% endif %}
    </div>
    <div style="height:150vh"></div>
{% endblock %}

carrent/carrentapp/templates/carrentapp/order_confirm_delete.html
{% extends 'carrentapp/base.html' %}

{% block hero_bar %}
    <section class="top-hero projects-hero" xmlns="http://www.w3.org/1999/html">
        <p class="top-hero-text text-light mb-0" style="font-size: 5rem; height: 40%; text-align: center">Na pewno usunąć?</p>
        <p class="top-hero-text text-light mt-0" style="font-size: 3rem; height: 40%; text-align: center">{{ object.car.brand.brand_name }} {{ object.car.car_model }}</p>
        <div class="hero-shadow bg-dark bg-gradient" style="height: 80%"></div>
    </section>
{% endblock %}

{% block section_one %}
    <div class="container border border-dark shadow bg-dark bg-gradient">
        <div class="row justify-content-md-center">
            <div class="col-sm-4 mt-2 mb-2">
                <table class="table table-responsive table-bordered table-hover table-striped table-dark">
                    <tr>
                        <td>Moc KM</td>
                        <td>{{ object.car.engine_power }}</td>
                    </tr>
                    <tr>
                        <td>Silnik</td>
                        <td>{{ object.car.get_engine_type_display }}</td>
                    </tr>
                    <tr>
                        <td>Skrzynia biegów</td>
                        <td>{{ object.car.get_gearbox_type_display }}</td>
                    </tr>
                    <tr>
                        <td>Kolor</td>
                        <td>{{ object.car.color }}</td>
                    </tr>
                    <tr>
                        <td>Liczba miejsc</td>
                        <td>{{ object.car.number_of_seats }}</td>
                    </tr>
                    <tr>
                        <td>Rok produkcji</td>
                        <td>{{ object.car.year_of_production }}</td>
                    </tr>
                    <tr>
                        <td>Data odbioru</td>
                        <td style="color: #007bff">{{ object.start_date }}</td>
                    </tr>
                    <tr>
                        <td>Data zwrotu</td>
                        <td style="color: crimson">{{ object.return_date }}</td>
                    </tr>
                    <tr style="color: green">
                        <td>Koszt całkowity</td>
                        <td style="color: lawngreen">{{ object.rent_cost }} PLN</td>
                    </tr>
                </table>
                <form method="post">
                    {% if object.is_past %}
                        <a href="{% url 'history_order' %}" class="btn btn-dark btn-lg">Cofnij do historii zamówien</a>
                        <input type="submit" value="Potwierdź usunięcie" class="btn btn-danger btn-lg disabled">
                        <p style="color: red; font-size: 2rem">Usuwanie minionych zamówień jest zabronione </p>
                    {% elif object.is_future %}
                        <a href="{% url 'future_order' %}" class="btn btn-dark btn-lg">Cofnij do zaplanowanych zamówien</a>
                        <input type="submit" value="Potwierdź usunięcie" class="btn btn-danger btn-lg">
                    {% else %}
                        <a href="{% url 'actual_order' %}" class="btn btn-dark btn-lg">Cofnij do aktuanych zamówien</a>
                        <input type="submit" value="Potwierdź usunięcie" class="btn btn-danger btn-lg disabled">
                        <p style="color: red; font-size: 2rem">Usuwanie rozpoczętych zamówień jest zabronione </p>
                    {% endif %}
                    {% csrf_token %}
                </form>
            </div>
            <div class="col-sm-8 mb-2 mt-2">
                <img class="img-fluid rounded float-end" src="{{ object.car.car_image.url }}" alt="{{ car.color }} samochod">
            </div>
        </div>
    </div>
{% endblock %}

carrent/carrentapp/templates/carrentapp/order_detail.html
{% extends 'carrentapp/base.html' %}

{% block hero_bar %}
    <section class="top-hero projects-hero" xmlns="http://www.w3.org/1999/html">
        <p class="top-hero-text text-light mb-0" style="font-size: 3rem; height: 40%; text-align: center">szczegóły Twojego zamówienia</p>
        <p class="top-hero-text text-light mt-0" style="font-size: 5rem; height: 40%; text-align: center">{{ object.car.brand.brand_name }} {{ object.car.car_model }}</p>
        <div class="hero-shadow bg-dark bg-gradient" style="height: 80%"></div>
    </section>
{% endblock %}

{% block section_one %}
    <div class="container border border-dark shadow bg-dark bg-gradient">
        <div class="row justify-content-md-center">
            <div class="col-sm-4 mt-2 mb-2">
                <table class="table table-responsive table-bordered table-hover table-striped table-dark">
                    <tr>
                        <td>Moc KM</td>
                        <td>{{ object.car.engine_power }}</td>
                    </tr>
                    <tr>
                        <td>Silnik</td>
                        <td>{{ object.car.get_engine_type_display }}</td>
                    </tr>
                    <tr>
                        <td>Skrzynia biegów</td>
                        <td>{{ object.car.get_gearbox_type_display }}</td>
                    </tr>
                    <tr>
                        <td>Kolor</td>
                        <td>{{ object.car.color }}</td>
                    </tr>
                    <tr>
                        <td>Liczba miejsc</td>
                        <td>{{ object.car.number_of_seats }}</td>
                    </tr>
                    <tr>
                        <td>Rok produkcji</td>
                        <td>{{ object.car.year_of_production }}</td>
                    </tr>
                    <tr>
                        <td>Data odbioru</td>
                        <td style="color: #007bff">{{ object.start_date }}</td>
                    </tr>
                    <tr>
                        <td>Data zwrotu</td>
                        <td style="color: crimson">{{ object.return_date }}</td>
                    </tr>
                    <tr style="color: green">
                        <td>Koszt całkowity</td>
                        <td style="color: lawngreen">{{ object.rent_cost }} PLN</td>
                    </tr>
                </table>
                {% if object.is_past %}
                    <a href="{% url 'history_order' %}" class="btn btn-dark btn-lg" style="font-size: large">Cofnij do historii</a>
                {% elif object.is_future %}
                    <a href="{% url 'future_order' %}" class="btn btn-dark btn-lg" style="font-size: large">Cofnij do zaplanowanych</a>
                    <a href ="{% url 'order_update' order.id %}" class="btn btn-success btn-lg" style="font-size: large">Zmień terminy</a>
                {% else %}
                    <a href="{% url 'actual_order' %}" class="btn btn-dark btn-lg" style="font-size: large">Cofnij do aktuanych zamówien</a>
                    <a href ="{% url 'order_update' order.id %}" class="btn btn-success btn-lg" style="font-size: large">Przedłuż najem</a>
                {% endif %}
            </div>
            <div class="col-sm-8 mb-2 mt-2">
                <img class="img-fluid rounded float-end" src="{{ object.car.car_image.url }}" alt="{{ car.color }} samochod">
            </div>
        </div>
    </div>
    <div style="height:100vh"></div>
{% endblock %}

carrent/carrentapp/templates/carrentapp/order_future.html
{% extends 'carrentapp/base.html' %}

{% block section_one %}
    <div class="container h-100 d-flex flex-column align-items-center text-dark text-center">
        {% if order_list.count < 1 %}
            <div style="height:15vh"></div>
            <h2>Brak wyników do wyświetlenia</h2>
        {% else %}
            <h2>Zaplanowane wypożyczenia</h2>
            <div style="height:5vh"></div>
            <table class="table table-responsive table-bordered table-hover table-striped table-dark">
                <thead>
                    <tr>
                        <th scope="col">Marka samochodu</th>
                        <th scope="col">Model samochodu</th>
                        <th scope="col">Numer rejestracyjny</th>
                        <th scope="col">Data wypożyczenia</th>
                        <th scope="col">Data zwrotu</th>
                        <th scope="col">Koszt wypożyczenia</th>
                        <th scope="col"></th>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <body>
                    {%  for order in order_list  %}
                        <tr class="table-primary">
                            <td> {{ order.car.brand }} </td>
                            <td> {{ order.car.car_model }}  </td>
                            <td> {{ order.car.plate_number }}  </td>
                            <td> {{ order.start_date }}  </td>
                            <td> {{ order.return_date }}  </td>
                            <td> {{ order.rent_cost }}  </td>
                            <td> <a href ="{% url 'order_detail' order.id %}" class="btn btn-info text-nowrap">Szczegóły</a></td>
                            <td> <a href ="{% url 'order_update' order.id %}" class="btn btn-primary text-nowrap">Zmień terminy</a></td>
                            <td> <a href ="{% url 'order_delete' order.id %}" class="btn btn-warning text-nowrap">Usuń</a></td>
                        </tr>
                    {% endfor %}
                </body>
            </table>
        {% endif %}
    </div>
    <div style="height:150vh"></div>
{% endblock %}

carrent/carrentapp/templates/carrentapp/order_history.html
{% extends 'carrentapp/base.html' %}

{% block section_one %}

<div class="container h-100 d-flex flex-column align-items-center text-dark text-center">
    {% if order_list.count < 1 %}
        <div style="height:15vh"></div>
        <h2>Brak wyników do wyświetlenia</h2>
    {% else %}
        <h2>Historia Twoich zamówień</h2>
        <div style="height:5vh"></div>
        <table class="table table-responsive table-bordered table-hover table-striped table-dark">
            <thead>
                <tr>
                    <th scope="col">Marka samochodu</th>
                    <th scope="col">Model samochodu</th>
                    <th scope="col">Numer rejestracyjny</th>
                    <th scope="col">Data wypożyczenia</th>
                    <th scope="col">Data zwrotu</th>
                    <th scope="col">Koszt wypożyczenia</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <body>
                {%  for order in page_obj  %}
                   <tr class="table-primary">
                        <td> {{ order.car.brand }}  </td>
                        <td> {{ order.car.car_model }}  </td>
                        <td> {{ order.car.plate_number }}  </td>
                        <td> {{ order.start_date }}  </td>
                        <td> {{ order.return_date }}  </td>
                        <td> {{ order.rent_cost }}  </td>
                        <td> <a href ="{% url 'order_detail' order.id %}" class="btn btn-info text-nowrap">Szczegóły</a></td>
                   </tr>
                {% endfor %}
            </body>
        </table>
    {% include 'carrentapp/paginator.html' %}
    {% endif %}
</div>
<div style="height:150vh"></div>
{% endblock %}